### ISSUE TITLE
Could we also have a wildcard mask displayed? 

### ISSUE THREAD

**Issue by vladola** [myokoo/alfred-subnetmask-workflow#1]
It would be useful when for example configuring ACLs.

Thank you!

**Comment by myokoo** [comment]
@vladola thanks you for your request.

I have displayed wildcard mask at [this commit](https://github.com/myokoo/alfred-subnetmask-workflow/pull/2/commits/ecf8fcc664200dad5d434ecc269748eb1b767eba).

Please try it.
Let me know If it is different from your intention.

**Comment by vladola** [comment]
Hey @myokoo - this is exactly what I needed, thanks a lot, that was quick 👍
